import { Inter } from 'next/font/google'
import './globals.css'
// import 'bootstrap/dist/css/bootstrap.css'
import Image from "next/image";
import Vercel from "../public/vercel.svg";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col justify-center m-4 items-center `}>
        <nav className='bg-slate-100 w-full'>
          {/* width & height automatically provided */}

        <Image src={Vercel} alt='head' blurDataURL="data:..." placeholder="blur" />
        </nav>
        {children}</body>
    </html>
  )
}
